name: esp_rainmaker_local_control
description: Library for locally controlling ESP Rainmaker devices with mDNS discovery.
version: 1.0.0-nullsafety.0
homepage: https://github.com/chmoore889/esp_local_control

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  multicast_dns: ^0.3.0
  http: ^0.13.2
  protobuf: ^2.0.0
  meta: ^1.3.0

  isolate_json: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
