name: esp_rainmaker_local_control
description: Library for locally controlling ESP Rainmaker devices with mDNS discovery.
version: 0.1.0+1
homepage: https://github.com/chmoore889/esp_local_control

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  multicast_dns: ^0.2.2
  http: ^0.12.2
  protobuf: ^1.1.0
  meta: ^1.2.4

  isolate_json: ^1.0.0+1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
